name: Deploy PR previews

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

concurrency: preview-${{ github.ref }}

env:
  PREVIEW_BASE_URL: https://beta-docs.dev.fiftyone.ai

jobs:
  deploy-preview:
    if: ${{ github.event.action != 'closed' }}
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/_publish.yml
    with:
      src-dir: site/
      dest-dir: pr-${{ github.event.number }}
    secrets: inherit

  leave-pr-comment:
    needs: deploy-preview
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: pr-preview
          message: |
            View preview at <br> ${{ env.PREVIEW_BASE_URL }}/pr-${{ github.event.number }}/index.html <br>

  clean-deployment:
    if: ${{ github.event.action == 'closed' }}
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/_clean_deployment.yml
    with:
      path: pr-${{ github.event.number }}
    secrets: inherit

  update-pr-comment:
    needs: clean-deployment
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: pr-preview
          message: |
            The preview for this PR has been removed
