---
name: pre-commit

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Run pre-commit
        uses: "voxel51/aloha-github-workflows/.github/actions/pre-commit@main"
        with:
          # HEAD is the PR merge commit `refs/pull/<PR_NUMBER>/merge`
          # HEAD^1 is the PR target branch (same as `origin/${{ github.event.pull_request.base.ref }}`)
          extra_args: --from-ref HEAD^1 --to-ref HEAD
